summary(datasets$Price)
summary(datasets$Magasins)
summary(datasets$Metro)
summary(datasets$People)
summary(datasets$Meanprice)
boxplot(datasets$Magasins,datasets$Price)
boxplot(datasets$Metro,datasets$Price)
boxplot(datasets$People,datasets$Price)
boxplot(datasets$MeanPrice,datasets$Price)
boxplot(datasets$Rasmer,datasets$Price)
cor(datasets)
cent<-lm(Price~Magasins+Metro+People+Meanprice+Rasmer,data=datasets)
summary(cent)
 cent1<-lm(Price~Magasins+Metro+People+Meanprice+Rasmer,data=datasets) 
 cent2<-lm(Price~Metro+People,data=datasets)
library(MASS)
 AIC(cent1,cent2)
cent1<-lm(Price~Magasins+Metro+People+Meanprice+Rasmer,data=datasets)
durbinWatsonTest(cent1)
ncvTest(cent1)
gqtest(cent1)
cent4<-lm(Price~Metro+People,data=datasetss)
predict(cent4)
centt<-as.data.frame(scale(datasets))
zcent<-lm(Price~Magasins+Metro+People+Meanprice+Rasmer,data=centt)
coef(zcent)

 

